language: php
php:
  - '7.0'

before_script:
  - composer install

script:
  - ./vendor/bin/phploc src/
  - ./vendor/bin/phpcpd src/
  - ./vendor/bin/phpcs src/ --standard=PSR2
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpmd src/ text phpmd.xml
